### ISSUE TITLE
Problem: m0_servers sections is mandatory in CDF even for the client-only nodes

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1401]
On the SAGE prototype cluster, there are server and client-only nodes. And if `m0_servers` section is not configured in the CDF for some client node, cfgen would fail with the error:

```
10:45 tkachuk1@sage-tier1-1:~$ hctl bootstrap --mkfs ~/sage-proto-cdf.yaml 
2020-11-17 10:46:01: Generating cluster configuration...cfgen: **ERROR** /home/users/jusers/tkachuk1/sage/sage-proto-cdf.yaml: Invalid cluster description

Error: Key m0_servers, expected by Dhall type:
List { io_disks : { data : List Text, meta_data : Optional Text }, runs_confd : Optional Bool }
is not present in YAML object:
data_iface: ib0
hostname: client-21
m0_clients:
  other: 80
  s3: 0
data_iface_type: o2ib

To learn more, run '/opt/seagate/cortx/hare/bin/../bin/cfgen --help-schema'.
```

To workaround the issue I specified the following for each client node:

```
    m0_servers: 
      - io_disks: 
          data: [] 
```

(Not sure whether it will work as needed though - whether it won't put io-services with empty disks list onto the client nodes. Will update on it.)

**Comment by andriytk** [comment]
Looks like the workaround does not work after all:

```
12:55 seagate@sage-cmu:sage$ hctl bootstrap --mkfs ~tkachuk1/sage-proto-cdf.yaml
2020-11-17 12:55:35: Generating cluster configuration...Traceback (most recent call last):
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 1741, in <module>
    main()
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 133, in main
    validate_cluster_desc(cluster_desc)
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 231, in validate_cluster_desc
    validate_nodes_desc(desc['nodes'])
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 267, in validate_nodes_desc
    f"{name}: Either 'runs_confd' or 'io_disks.data' must be set"
AssertionError: client-21: Either 'runs_confd' or 'io_disks.data' must be set
```
