### ISSUE TITLE
'hctl status' hangs and gives 'connection reset by peer' error 

### ISSUE THREAD

**Issue by rupasree-roy** [Seagate/cortx-hare#1444]
'hctl status' hangs and on pressing ctrl+C gives a bunch of 'connection reset by peer' error as follows: 
```
^CTraceback (most recent call last):
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/seagate/cortx/hare/libexec/hare-status", line 96, in kv_item
    val = cns.kv.get(key, recurse=recurse)[1]
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/consul/base.py", line 554, in get
    params=params)
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/consul/std.py", line 22, in get
    self.session.get(uri, verify=self.verify, cert=self.cert)))
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/seagate/cortx/hare/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/rroy/cortx/cortx-hare/hax/hax/util.py", line 117, in wrapper
    result = f(*args, **kwds)
  File "/opt/seagate/cortx/hare/libexec/hare-status", line 246, in show_text_status
    pools = sns_pools(cns)
  File "/opt/seagate/cortx/hare/libexec/hare-status", line 124, in sns_pools
    for x in kv_item(cns, 'm0conf/pools/', recurse=True)]
  File "/opt/seagate/cortx/hare/libexec/hare-status", line 100, in kv_item
    raise HAConsistencyException('Could not access Consul KV') from e
hax.exception.HAConsistencyException
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/seagate/cortx/hare/libexec/hare-status", line 289, in <module>
    sys.exit(main())
  File "/opt/seagate/cortx/hare/libexec/hare-status", line 283, in main
    show_text_status(cns)
  File "/home/rroy/cortx/cortx-hare/hax/hax/util.py", line 131, in wrapper
    sleep(wait_seconds)
KeyboardInterrupt
```

**Comment by knekrasov** [comment]
@rupasree-roy Thanks for submitting the issue.

The exception that you get when pressing Ctrl-C is quite self-descriptive: Consul KV was not accessible. Such an error is an intermittent one, that's why "hctl status" was silently retrying the operation (which looked like "hang"). 

So it is more interesting why Consul was not functional. Can you provide more details how to reproduce the issue? Journald logs would be also much appreciated (at least - it would be nice to see consul-related logs like this: `sudo journalctl  --unit="hare-consul-agent.service"`)

**Comment by rupasree-roy** [comment]
@knekrasov I actually installed everything (hare and motr) from scratch and things are working now. 'hctl status' doesn't hang anymore. 

However, here are few stuffs which I had tried/checked before re-installing everything: 
* Disabled firewall and tried
* consul agent was working as shown below: 
```
pgrep -a consul
2647 consul agent -node super7-cortexvm-7.7-ramallo.frmt.seagate.com -node-id 090c9559-fbb8-3861-b919-7f208370bb15 -bind 192.168.41.122 -client 127.0.0.1 192.168.41.122 -config-dir=/var/lib/hare/consul-server-conf -data-dir=/var/lib/hare/consul-192.168.41.122 -ui -bootstrap-expect 1
3301 consul watch -type=keyprefix -prefix eq/ /home/rroy/cortx/cortx-hare/utils/proto-rc
```
* hax and m0d processes was running as well
```
pgrep -a hax
3540 /home/rroy/cortx/cortx-hare/.py3venv/bin/python3.6 /opt/seagate/cortx/hare/bin/hax
```
and 
```
pgrep -a m0d
4049 /home/rroy/cortx/cortx-motr/motr/.libs/lt-m0d -e lnet:192.168.41.122@tcp:12345:2:1 -A linuxstob:addb-stobs -f <0x7200000000000001:0x9> -T linux -S stobs -D db -m 65536 -q 16 -w 8 -c /etc/motr/confd.xc -H 192.168.41.122@tcp:12345:1:1 -U -r 1073741824
4715 /home/rroy/cortx/cortx-motr/motr/.libs/lt-m0d -e lnet:192.168.41.122@tcp:12345:2:2 -A linuxstob:addb-stobs -f <0x7200000000000001:0xc> -T ad -S stobs -D db -m 65536 -q 16 -w 8 -H 192.168.41.122@tcp:12345:1:1 -U -r 1073741824
```
Since things are working now, don't think `sudo journalctl ...`  will give any valuable information.

**Comment by vaibhavparatwar** [comment]
Closing this issue right now. if seen again, please reopen

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
