### ISSUE TITLE
hctl bootstrap does not show which node has the problem with IP config

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1487]
```
[seagate@sage-tier1-1 ~]$ hctl bootstrap --mkfs /home/users/project/SHARED/sage-update-20201028/sage-proto-cdf.yaml
2021-02-03 11:03:22: Generating cluster configuration...Traceback (most recent call last):
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 1757, in <module>
    main()
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 133, in main
    validate_cluster_desc(cluster_desc)
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 235, in validate_cluster_desc
    validate_nodes_desc(desc['nodes'])
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 251, in validate_nodes_desc
    '\n'.join('  ' + x.ipaddr for x in nodes)
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 251, in <genexpr>
    '\n'.join('  ' + x.ipaddr for x in nodes)
TypeError: must be str, not NoneType
```

**Comment by knekrasov** [comment]
@andriytk Can you give a sample CDF where the issue can be reproduced?

**Comment by andriytk** [comment]
@knekrasov, select any for several nodes from `cfgen/examples/` dir.
