### ISSUE TITLE
Server restart gets stuck because of hax

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1637]
When some server process crashes (like ios) and tries to restart, hax gets entrypoint request from it. But it won't reply on it until it delivers the failed notification about this process to all cluster members beforehand.

Now, among these cluster members there might be some client applications which were failed (crashed) also (utilities, like m0cp). And since such client apps are not monitored by Consul - hax won't fail them and won't disconnect ha_links with them, and still would try to deliver msgs to them, including the failed notifications. Which, of course, will never succeed.

So we are not in the situation when any process restart gets essentially stuck because hax does not reply to their entrypoint reqs. Here is the snip of system log of such a situation:

```
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,820 [DEBUG] {Dummy-1} Received entrypoint request from remote endpoint '192.168.180.171@tcp:12345:2:2', process fid = 0x7200000000000001:0xc The request will be processed in another thread.
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,828 [DEBUG] {qconsumer} Got BroadcastHAStates(states=[HAState(fid=0x7200000000000001:0xc, status=OK)], reply_to=None) message from queue
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,828 [INFO] {qconsumer} HA states: [HAState(fid=0x7200000000000001:0xc, status=OK)]
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,840 [DEBUG] {qconsumer} item.status passing
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,877 [INFO] {qconsumer} node: centos79 proc: 0x7200000000000001:0xc current status: ServiceHealth.OFFLINE
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,877 [DEBUG] {qconsumer} Broadcasting HA states [HAState(fid=0x7200000000000001:0xc, status=OFFLINE)] over ha_link
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,878 [DEBUG] {qconsumer} Waiting for the next message
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,878 [DEBUG] {qconsumer} Got FirstEntrypointRequest(reply_context=140267995040480, req_id=0x0:0x13, remote_rpc_endpoint='192.168.180.171@tcp:12345:2:2', process_fid=0x7200000000000001:0xc, git_rev='7e8923cc905c50ef2755be248286b38a45b760d7', pid=58947, is_first_request=1) message from queue
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,878 [DEBUG] {qconsumer} first entrypoint request, broadcast FAILED
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,878 [DEBUG] {qconsumer} Broadcasting HA states [HAState(fid=0x7200000000000001:0xc, status=FAILED)] over ha_link
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,885 [DEBUG] {qconsumer} Process fid=0x7200000000000001:0xc encloses 8 services as follows: [FidWithType(fid=0x7300000000000001:0x25, service_type='addb2'), FidWithType(fid=0x7300000000000001:0x26, service_type='cas'), FidWithType(fid=0x7300000000000001:0x28, service_type='fdmi'), FidWithType(fid=0x7300000000000001:0xe, service_type='ios'), FidWithType(fid=0x7300000000000001:0x27, service_type='iscs'), FidWithType(fid=0x7300000000000001:0xd, service_type='rms'), FidWithType(fid=0x7300000000000001:0x24, service_type='sns_reb'), FidWithType(fid=0x7300000000000001:0x23, service_type='sns_rep')]
Jun 08 18:08:38 centos79 hare-hax[54198]: motr[54198]:  d910   WARN  [ha/halon/interface.c:1111:m0_halon_interface_send]  hl=0x7f928c008f10 ep=192.168.180.171@tcp:12345:1:1 epoch=0 tag=57 type=2
Jun 08 18:08:38 centos79 hare-hax[54198]: motr[54198]:  d910   WARN  [ha/halon/interface.c:1111:m0_halon_interface_send]  hl=0x7f928c01e570 ep=192.168.180.171@tcp:12345:2:1 epoch=0 tag=45 type=2
Jun 08 18:08:38 centos79 hare-hax[54198]: motr[54198]:  d910   WARN  [ha/halon/interface.c:1111:m0_halon_interface_send]  hl=0x7f92b020f240 ep=192.168.180.171@tcp:12345:4:1 epoch=0 tag=15 type=2
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,885 [DEBUG] {qconsumer} Broadcast HA state complete with the following message_ids = [MessageId(0x7f928c008f10, 57), MessageId(0x7f928c01e570, 45), MessageId(0x7f92b020f240, 15)]
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,886 [DEBUG] {qconsumer} waiting for broadcast of [MessageId(0x7f928c008f10, 57), MessageId(0x7f928c01e570, 45), MessageId(0x7f92b020f240, 15)] for ep: 192.168.180.171@tcp:12345:2:2
Jun 08 18:08:38 centos79 hare-hax[54198]: motr[54198]:  e920   WARN  [ha/halon/interface.c:433:halon_interface_msg_is_delivered_cb]  hl=0x7f928c01e570 ep=192.168.180.171@tcp:12345:2:1 tag=45
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,893 [INFO] {Dummy-1} Delivered to endpoint'192.168.180.171@tcp:12345:2:1', process fid = 0x0:0x0tag= 45
Jun 08 18:08:38 centos79 hare-hax[54198]: motr[54198]:  e920   WARN  [ha/halon/interface.c:433:halon_interface_msg_is_delivered_cb]  hl=0x7f928c008f10 ep=192.168.180.171@tcp:12345:1:1 tag=57
Jun 08 18:08:38 centos79 hare-hax[54198]: 2021-06-08 18:08:38,894 [INFO] {Dummy-1} Delivered to endpoint'192.168.180.171@tcp:12345:1:1', process fid = 0x0:0x0tag= 57
Jun 08 18:08:40 centos79 hare-hax[54198]: 2021-06-08 18:08:40,340 [DEBUG] {fs-stats-updater} The following statuses received: [(ServiceData(node='centos79', fid=0x7200000000000001:0x9, ip_addr='192.168.180.171', address='192.168.180.171@tcp:12345:2:1'), 'M0_CONF_HA_PROCESS_STARTED'), (ServiceData(node='centos79', fid=0x7200000000000001:0xc, ip_addr='192.168.180.171', address='192.168.180.171@tcp:12345:2:2'), 'M0_CONF_HA_PROCESS_STOPPED')]
Jun 08 18:08:48 centos79 hare-hax[54198]: motr[54198]:  e960   WARN  [ha/link.c:1285:ha_link_outgoing_fop_replied]  rc=-110 nr=1 hl=0x7f92b020f240 ep=192.168.180.171@tcp:12345:4:1 lq_tags=(confirmed=15 delivered=15 next=15 assign=17)
Jun 08 18:08:48 centos79 hare-hax[54198]: motr[54198]:  e960   WARN  [ha/link.c:1289:ha_link_outgoing_fop_replied]  old_rc=0 old_nr=14 hl=0x7f92b020f240 ep=192.168.180.171@tcp:12345:4:1
Jun 08 18:08:59 centos79 hare-hax[54198]: motr[54198]:  e960   WARN  [ha/link.c:1285:ha_link_outgoing_fop_replied]  rc=-110 nr=2 hl=0x7f92b020f240 ep=192.168.180.171@tcp:12345:4:1 lq_tags=(confirmed=15 delivered=15 next=15 assign=17)
Jun 08 18:09:08 centos79 hare-hax[54198]: 2021-06-08 18:09:08,896 [ERROR] {qconsumer} **ERROR**
Jun 08 18:09:08 centos79 hare-hax[54198]: Traceback (most recent call last):
Jun 08 18:09:08 centos79 hare-hax[54198]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/handler.py", line 179, in _do_work
Jun 08 18:09:08 centos79 hare-hax[54198]: self.herald.wait_for_all(HaLinkMessagePromise(ids))
Jun 08 18:09:08 centos79 hare-hax[54198]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/motr/delivery.py", line 106, in wait_for_all
Jun 08 18:09:08 centos79 hare-hax[54198]: self._verify_delivered(promise, timeout_sec)
Jun 08 18:09:08 centos79 hare-hax[54198]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/motr/delivery.py", line 61, in _verify_delivered
Jun 08 18:09:08 centos79 hare-hax[54198]: str(timeout_sec) + ' seconds timeout')
Jun 08 18:09:08 centos79 hare-hax[54198]: hax.exception.NotDelivered
Jun 08 18:09:08 centos79 hare-hax[54198]: 2021-06-08 18:09:08,897 [DEBUG] {qconsumer} Waiting for the next message
Jun 08 18:09:10 centos79 hare-hax[54198]: 2021-06-08 18:09:10,381 [DEBUG] {fs-stats-updater} The following statuses received: [(ServiceData(node='centos79', fid=0x7200000000000001:0x9, ip_addr='192.168.180.171', address='192.168.180.171@tcp:12345:2:1'), 'M0_CONF_HA_PROCESS_STARTED'), (ServiceData(node='centos79', fid=0x7200000000000001:0xc, ip_addr='192.168.180.171', address='192.168.180.171@tcp:12345:2:2'), 'M0_CONF_HA_PROCESS_STOPPED')]
Jun 08 18:09:21 centos79 hare-hax[54198]: motr[54198]:  e960   WARN  [ha/link.c:1285:ha_link_outgoing_fop_replied]  rc=-110 nr=4 hl=0x7f92b020f240 ep=192.168.180.171@tcp:12345:4:1 lq_tags=(confirmed=15 delivered=15 next=15 assign=17)
Jun 08 18:09:40 centos79 hare-hax[54198]: 2021-06-08 18:09:40,426 [DEBUG] {fs-stats-updater} The following statuses received: [(ServiceData(node='centos79', fid=0x7200000000000001:0x9, ip_addr='192.168.180.171', address='192.168.180.171@tcp:12345:2:1'), 'M0_CONF_HA_PROCESS_STARTED'), (ServiceData(node='centos79', fid=0x7200000000000001:0xc, ip_addr='192.168.180.171', address='192.168.180.171@tcp:12345:2:2'), 'M0_CONF_HA_PROCESS_STOPPED')]
Jun 08 18:10:05 centos79 hare-hax[54198]: motr[54198]:  e960   WARN  [ha/link.c:1285:ha_link_outgoing_fop_replied]  rc=-110 nr=8 hl=0x7f92b020f240 ep=192.168.180.171@tcp:12345:4:1 lq_tags=(confirmed=15 delivered=15 next=15 assign=17)
Jun 08 18:10:09 centos79 hare-hax[54198]: 2021-06-08 18:10:09,234 [DEBUG] {qconsumer} Got BroadcastHAStates(states=[HAState(fid=0x7200000000000001:0xc, status=FAILED)], reply_to=None) message from queue
Jun 08 18:10:09 centos79 hare-hax[54198]: 2021-06-08 18:10:09,234 [INFO] {qconsumer} HA states: [HAState(fid=0x7200000000000001:0xc, status=FAILED)]
Jun 08 18:10:09 centos79 hare-hax[54198]: 2021-06-08 18:10:09,248 [DEBUG] {qconsumer} item.status warning
Jun 08 18:10:09 centos79 hare-hax[54198]: 2021-06-08 18:10:09,269 [INFO] {qconsumer} node: centos79 proc: 0x7200000000000001:0xc current status: ServiceHealth.STOPPED
Jun 08 18:10:09 centos79 hare-hax[54198]: 2021-06-08 18:10:09,284 [DEBUG] {qconsumer} Broadcasting HA states [] over ha_link
Jun 08 18:10:09 centos79 hare-hax[54198]: 2021-06-08 18:10:09,284 [DEBUG] {qconsumer} Waiting for the next message
Jun 08 18:10:10 centos79 hare-hax[54198]: 2021-06-08 18:10:10,477 [DEBUG] {fs-stats-updater} The following statuses received: [(ServiceData(node='centos79', fid=0x7200000000000001:0x9, ip_addr='192.168.180.171', address='192.168.180.171@tcp:12345:2:1'), 'M0_CONF_HA_PROCESS_STARTED'), (ServiceData(node='centos79', fid=0x7200000000000001:0xc, ip_addr='192.168.180.171', address='192.168.180.171@tcp:12345:2:2'), 'M0_CONF_HA_PROCESS_STOPPED')]
Jun 08 18:10:40 centos79 hare-hax[54198]: 2021-06-08 18:10:40,539 [DEBUG] {fs-stats-updater} The following statuses received: [(ServiceData(node='centos79', fid=0x7200000000000001:0x9, ip_addr='192.168.180.171', address='192.168.180.171@tcp:12345:2:1'), 'M0_CONF_HA_PROCESS_STARTED'), (ServiceData(node='centos79', fid=0x7200000000000001:0xc, ip_addr='192.168.180.171', address='192.168.180.171@tcp:12345:2:2'), 'M0_CONF_HA_PROCESS_STOPPED')]
Jun 08 18:10:50 centos79 hare-hax[54198]: motr[54198]:  ed00   WARN  [fop/fom.c:362:hung_fom_notify]  FOP HUNG[[131:225357374] seconds in processing]: fom=0x7f927c07b960, fop 0x7f927c07ba18[117] phase: M0_HES_REPLY_WAIT
Jun 08 18:11:01 centos79 hare-hax[54198]: motr[54198]:  ed00   WARN  [fop/fom.c:362:hung_fom_notify]  FOP HUNG[[142:239780923] seconds in processing]: fom=0x7f927c07b960, fop 0x7f927c07ba18[117] phase: M0_HES_REPLY_WAIT
```

**Comment by andriytk** [comment]
I would suggest to add some timer (like 1 min) into hax for such client apps which are not monitored by Consul (utilities, like m0cp etc.) and disconnect ("fail") them if ha_link cannot deliver any msgs to them within the timeout.

@max-seagate what do you think?

**Comment by vaibhavparatwar** [comment]
@mssawant @knekrasov see if we need to create a JIRA ticket for this and take this up on priority.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

[~752700] this means we have an EPIC (a parent feature JIRA) to which these issues created by github are linked for timebeing until we get a proper EPIC id for github/community issues

**Comment by vaibhavparatwar** [comment]
@andriytk is this still valid issue? cc @SunilSavanurSeagate @mssawant

**Comment by vaibhavparatwar** [comment]
@andriytk are we still seeing this in current architecture (K8s) ? cc @SunilSavanurSeagate @mssawant

**Comment by vaibhavparatwar** [comment]
@andriytk do we still see this issue?

**Comment by vaibhavparatwar** [comment]
@andriytk  are we still seeing this? Is this bug still valid? cc @SunilSavanurSeagate @mssawant

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

[~520414] Is this issue seen recently? cc [~520513]

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
